format = """
[](#191724)\
$python\
$username\
[](bg:#26233a fg:#191724)\
$directory\
[](fg:#26233a bg:#31748f)\
$git_branch\
[](fg:#31748f bg:#61ffca)\
$docker_context\
[](fg:#61ffca bg:#a277ff)\
$time\
[ ](fg:#a277ff)\
"""
command_timeout = 1000

[username]
show_always = true
style_user = "bg:#191724 fg:#e0def4"
style_root = "bg:#191724 fg:#a277ff"
format = '[$user ]($style)'

[directory]
style = "bg:#29263c fg:#e0def4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#9ccfd8 fg:#191724"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#61ffca fg:#191724"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#9ccfd8 fg:#191724"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#9ccfd8 fg:#191724"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#f694ff fg:#e0def4"
format = '[ $symbol $branch ]($style)'

[git_status]
disabled = true
style = "bg:#f694ff fg:#e0def4"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#9ccfd8 fg:#191724"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#9ccfd8 fg:#191724"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#9ccfd8 fg:#191724"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#9ccfd8 fg:#191724"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#9ccfd8 fg:#191724"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#9ccfd8 fg:#191724"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#29263c fg:#f6c177"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#9ccfd8 fg:#191724"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#a277ff fg:#191724"
format = '[ $time ]($style)'
